[libdefaults]
    default_realm = HERCULES.HTB
    dns_lookup_kdc = false
    dns_lookup_realm = false
    rdns = false
    dns_canonicalize_hostname = false
    forwardable = true
    ticket_lifetime = 24h
    default_ccache_name = FILE:/tmp/krb5cc_%{uid}

[realms]
    HERCULES.HTB = {
        kdc = 10.129.242.196
        admin_server = 10.129.242.196
        default_domain = hercules.htb
    }

[domain_realm]
    .hercules.htb = HERCULES.HTB
    hercules.htb = HERCULES.HTB
